export interface SpanishNameDictionaryEntry {
  pattern?: string;
  replacement: string;
}

export const SPANISH_NAME_DICTIONARY: SpanishNameDictionaryEntry[] = [
  {
    replacement:
      "Universidad de los Andes, Vicerrectorado Administrativo, Oficina de seguros ULA (Ofiseula)",
  },
  {
    replacement:
      "Universidad de los Andes Vicerrectorado Académico, Consejo de Desarrollo Curricular",
  },
  { replacement: "Víctor Segundo Vargas Rodríguez" },
  { replacement: "Ana Thais Núñez" },
  { replacement: "Jesús A. Duarte M." },
  { replacement: "Eugenio Montilla" },
  { replacement: "Juana Márquez de Rizzo" },
  { replacement: "Gustavo A. Moreno V." },
  { replacement: "José Américo Rondón" },
  { replacement: "María del Rosario Muñoz Carrillo" },
  { replacement: "Miguel Arturo Moreno M." },
  { replacement: "Josefa  Moreno" },
  { replacement: "Rafael A. Pinto Angulo" },
  { replacement: "Rosalba Briceño de Alvarado" },
  { replacement: "Imera Nava de Utria" },
  { replacement: "Rosario H. Buttaci S." },
  { replacement: "Jesús Juan  Muñoz Dávila" },
  { replacement: "AIMARA LOBO" },
  { replacement: "Irma Martínez" },
  { replacement: "Segundo Quiroz" },
  { replacement: "Eduardo Juárez" },
  { replacement: "Nelly R. Pineda de Andara" },
  { replacement: "Randa Jazzan" },
  { replacement: "Rebeca Barillas" },
  { replacement: "José Juan Torres" },
  { replacement: "Carolina Álvarez Gómez" },
  { replacement: "Dayana L. Mendez C." },
  { replacement: "Amira Dayana Narváez Fagre" },
  { replacement: "Daniel Briceño" },
  { replacement: "Zoraida Morales" },
  { replacement: "Omaira J. Rodríguez de Barroeta" },
  { replacement: "Jesús A. Africano P." },
  { replacement: "Zaira Quijada Vazquez" },
  { replacement: "Froilana Azuaje" },
  { replacement: "Jacqueline Mejía" },
  { replacement: "Josefina Barrios de Montilva" },
  { replacement: "Elda Gutiérrez" },
  { replacement: "Ramón M.  Torres R." },
  { replacement: "Román Rodríguez Salón" },
  { replacement: "Ramón Domínguez" },
  { replacement: "Isamar Moreno" },
  { replacement: "Iván Alarcón" },
  { replacement: "Aníbal López" },
  { replacement: "Maribel Cuevas" },
  { replacement: "Xiomara Carrero" },
  { replacement: "Annuar Younesse" },
  { replacement: "Gustavo Uzcategui" },
  { replacement: "Dante Pino Pascucci" },
  { replacement: "Sucesión Núñez Arteaga" },
  {
    replacement: "Sucesión José María Torres / Ana Socorro de Torres",
  },
  { replacement: "Pierina Desantiago" },
  { replacement: "Carmen Chacón" },
  { replacement: "Iván Maldonado" },
  { replacement: "Feliciana Monsalve" },
  { replacement: "Nazario Nieto" },
  { replacement: "María Montilla" },
  { replacement: "María A. Araujo" },
  { replacement: "Dixon Rondón Rondón" },
  { replacement: "Nora Uzcategui" },
  { replacement: "Socorro C. Rodríguez M." },
  { replacement: "María Luz Seijas" },
  { replacement: "Leonor Vázquez de Labarca" },
  { replacement: "Germán Morales" },
  { replacement: "Rafael Serrano" },
  { replacement: "Lizzeth Guerrero" },
  { replacement: "Heberto Roque" },
  { replacement: "Luis Vera" },
  { replacement: "Abdallah Suleiman" },
  { replacement: "Faryer Calderón" },
  { replacement: "Valentín García" },
  { replacement: "María Aranguren" },
  { replacement: "José Gómez" },
  { replacement: "Marianela Coromoto Erazo Albornoz" },
  { replacement: "Carmen Maldonado" },
  { replacement: "Angélica Serva" },
  { replacement: "María Ghini" },
  { replacement: "Claudia Graciano" },
  { replacement: "Idiolinda Arellano Cruz" },
  { replacement: "Iván Ospina" },
  { replacement: "Thair Salah" },
  { pattern: "maria gil", replacement: "María Gil" },
  { pattern: "delia avila", replacement: "Delia Ávila" },
  { replacement: "Silvestre Guerrero" },
  { pattern: "hugo perez", replacement: "Hugo Pérez" },
  { replacement: "María Gil" },
  { replacement: "José Parra" },
  { replacement: "Ever Plaza" },
  { replacement: "María Delia Ávila" },
  { replacement: "José Plaza" },
  { pattern: "merida", replacement: "Mérida" },
  { pattern: "mérida", replacement: "Mérida" },
  { pattern: "materiales los andes", replacement: "Materiales Los Andes" },
  {
    pattern: "inversiones arte decoraciones",
    replacement: "Inversiones Arte Decoraciones",
  },
  {
    pattern: "llave maestra de venezuela",
    replacement: "Llave Maestra de Venezuela",
  },
  { pattern: "venezuela", replacement: "Venezuela" },
  { pattern: "autorepuestos fredmar", replacement: "Autorepuestos Fredmar" },
  { pattern: "fredmar", replacement: "Fredmar" },
  { pattern: "copicentro merida", replacement: "Copicentro Mérida" },
  {
    pattern: "super tiendas de todito",
    replacement: "Super Tiendas de Todito",
  },
  { pattern: "super tiendas d todito", replacement: "Super Tiendas de Todito" },
  { pattern: "casa electra", replacement: "Casa Electra" },
  { pattern: "bcv", replacement: "BCV" },
  { pattern: "torre a", replacement: "Torre A" },
  { pattern: "torre b", replacement: "Torre B" },
  { pattern: "torre a y b", replacement: "Torre A y B" },
];
